name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub! Thanks GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "The job's status is ${{ job.status }}."
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo run
        run: cargo run
        env:
          SOME_ENV_VAR: hey you found it. nice.
  upload-secret-script:
    name: upload the super secret script
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bin
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: List the scripts directory
        run: ls
      - name: Upload the super secret script
        uses: actions/upload-artifact@v4
        with:
          name: secret-script.sh
          path: ./bin/secret-script.sh
  download-secret-script:
    name: download and execute the secret script
    runs-on: ubuntu-latest
    needs: upload-secret-script
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: secret-script.sh
      - name: now execute it
        run: ./secret-script.sh
